### ISSUE TITLE
【提议】【GDScript】引入`private`和`protected`关键字

### ISSUE THREAD

**Issue by Lazy-Rabbit-2001** [Wedot-Engine/WeDot#12]
目前本人正在在Redot仓库里开发该功能，详情可关注：htt删ps://github.c除om/Redot-E我ngine/redot-eng们ine/pull/734（防止目标pr引用到本仓库就先这样做了，访问的时候记得删掉链接中的防链接汉字就行）
Redot那边合并以后我就第一时间转过来再pr一个

# 关键字解释

默认情况下，不被`private`和`protected`关键字修饰的成员的访问权限是公开的。
目前，这两个关键字只能修饰成员常量、变量、信号和函数（以下简称“成员”），且必须位于`static`的前方，否则会报错。

## `private`

被该关键字修饰的成员，只能通过当前类访问：
```GDScript
# A类
private static var a = 1
# B类
var s = A.a # 报错
# C类，继承自A类
var t = A.a # 也报错
```

## `protected`

被该关键字修饰的成员，只能通过声明该成员的类及其子类访问
```GDScript
# A类
protected static var a = 1
# B类
var s = A.a # 报错
# C类，继承自A类
var t = A.a # 不报错
```

## 共有特性
* 被这两个关键字修饰的成员，除非被`@export`注解及其衍生注解修饰，否则不会使其在自动生成的文档中显示，即便尝试用`##`强行使其显示也不行
* 这两个修饰词***只能二选其一使用***。

## 注意事项

* Godot里有一些诸如`set()`、`get()`和`call()`这些性质的反射函数（也包括通过`[]`对成员进行访问），`private`和`protected`不会对其起任何作用。一是因为诸如Java、C#等语言本身就支持通过反射跨权限访问一些私有或受保护属性，二是这些函数改起源码来十分麻烦，且因为高频调用，导致如果直接插入本来就比较吃性能的访问检查，将会大幅度拖慢引擎及游戏的整体运行速度。
* 如果出现链式访问，则总是以当前操作类为访问类。看以下代码：
```GDScript
class D:
    private var a = 1

class E:
    var s = D.new()

class F:
    var t = E.new()

    func foo():
        t.s.a = 2 # 此时F就是当前操作类，即访问类，此时只检测类F与类D的关系
```

**Comment by yythlj** [comment]
强烈反对，如果要变成强权限，为什么不直接unity

和python一样语法简单优雅，高效开发才是godot的特色（我作为5年经验与主程序的建议）

代码规范通过review可以控制。而不喜欢牺牲每个人的开发效率和维护效率，来做使得效率更低的没意义的事

我知道你出发点是想更好维护改源码，但是有了这个可以预想，插件就会变得就像java一样，一堆没丁点大的功能一个场景一个库就因为作者乱加权限
