### ISSUE TITLE
社区仓库建设项目跟进

### ISSUE THREAD

**Issue by PJ-568** [Wedot-Engine/WeDot#5]
- [x] #9
- [x] #10
- [x] #11
- [X] 是否有意向将仓库迁移至如 `WeDot Engine/WeDot` ？这似乎更符合 WeDot 引擎的不涉立场、去中心化的思想，也方便多个延申（网页、文档、社区等）项目的托管和维护。

---

我很乐意对网页、文档和 icon 设计做出一份贡献。

**Comment by GodotHan** [comment]
我认为我们首先要做的将仓库迁移至WeDotEngine下，然后创立ToDo仓库，进行仓库管理。维护官网与文档暂时人手稀缺

**Comment by PJ-568** [comment]
[Wedot-Engine](https://github.com/Wedot-Engine) 已创建，请通过邀请。

**Comment by PJ-568** [comment]
本仓库应转移至 [Wedot-Engine/WeDot-Engine](https://github.com/Wedot-Engine/WeDot-Engine)。

**Comment by kain365** [comment]
我搞了个LOGO, 四耳猫... 明确的GODOT分支
![378195586-fcbdc3a4-9675-4dbb-aab2-19ea8c722652](https://github.com/user-attachments/assets/a730bb03-0c29-41dd-9440-b68ff573c78a)

**Comment by PJ-568** [comment]
我们的项目知名度太低。是否考虑运营 X 和 Reddit 账户和一个论坛？

**Comment by PJ-568** [comment]
Godot 的文档是基于 Sphinx 构建，用 reStructuredText 编写的……我们要跟进吗？

**Comment by vonweller** [comment]
> Godot 的文档是基于 Sphinx 构建，用 reStructuredText 编写的……我们要跟进吗？

我觉得对于本土化特殊的添加需要加入文档，其余部分应当跟随godot的文档

**Comment by hmrbh** [comment]
> 我们的项目知名度太低。是否考虑运营 X 和 Reddit 账户和一个论坛？

我认为这是一个可行的方案。

**Comment by hmrbh** [comment]
X上有庞大的开发者社区
